<?php
// app/Services/ExportService.php
// Handles CSV, Excel (XLSX via SpreadsheetML), JSON, and PDF exports

namespace App\Services;

class ExportService
{
    // ── CSV Export ─────────────────────────────────────────────────────────
    public static function csv(array $data, array $headers, string $filename): never
    {
        $filename = self::sanitizeFilename($filename) . '.csv';
        header('Content-Type: text/csv; charset=UTF-8');
        header("Content-Disposition: attachment; filename=\"{$filename}\"");
        header('Cache-Control: no-cache, no-store, must-revalidate');
        header('Pragma: no-cache');

        $out = fopen('php://output', 'w');
        // BOM for Excel UTF-8
        fputs($out, "\xEF\xBB\xBF");
        fputcsv($out, $headers);
        foreach ($data as $row) {
            fputcsv($out, is_array($row) ? array_values($row) : [$row]);
        }
        fclose($out);
        exit;
    }

    // ── JSON Export ────────────────────────────────────────────────────────
    public static function json(array $data, array $meta = [], string $filename = 'export'): never
    {
        $filename = self::sanitizeFilename($filename) . '.json';
        header('Content-Type: application/json; charset=UTF-8');
        header("Content-Disposition: attachment; filename=\"{$filename}\"");
        header('Cache-Control: no-cache');

        echo json_encode([
            'meta'      => array_merge(['exported_at' => date('c'), 'total_records' => count($data)], $meta),
            'data'      => $data,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
        exit;
    }

    // ── Excel (XLSX via SpreadsheetML) ────────────────────────────────────
    public static function excel(array $data, array $headers, string $filename, string $sheetName = 'Report'): never
    {
        $filename = self::sanitizeFilename($filename) . '.xlsx';
        $xlsx     = self::buildXlsx($data, $headers, $sheetName);

        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header("Content-Disposition: attachment; filename=\"{$filename}\"");
        header('Content-Length: ' . strlen($xlsx));
        header('Cache-Control: no-cache');

        echo $xlsx;
        exit;
    }

    // ── PDF Export (via TCPDF) ─────────────────────────────────────────────
    public static function pdf(
        string $title,
        string $html,
        string $filename,
        string $orientation = 'P'
    ): never {
        $filename = self::sanitizeFilename($filename) . '.pdf';

        $pdf = new \TCPDF($orientation, 'mm', 'A4', true, 'UTF-8', false);
        $pdf->SetCreator('AccountingPro');
        $pdf->SetTitle($title);
        $pdf->SetAuthor('AccountingPro ERP');
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        $pdf->SetMargins(15, 15, 15);
        $pdf->SetAutoPageBreak(true, 20);
        $pdf->AddPage();

        // Footer
        $pdf->SetFont('helvetica', 'I', 8);
        $pdf->SetTextColor(150, 150, 150);
        $pdf->Cell(0, 6, "Generated by AccountingPro ERP on " . date('d M Y H:i') . " | Page 1", 0, 1, 'R');
        $pdf->Ln(2);

        $pdf->SetFont('dejavusans', '', 9);
        $pdf->SetTextColor(0, 0, 0);
        $pdf->writeHTML($html, true, false, true, false, '');

        $pdf->Output($filename, 'D');
        exit;
    }

    // ── HTML-to-PDF helper for tabular report data ─────────────────────────
    public static function buildReportHtml(
        string $reportTitle,
        array  $columns,
        array  $data,
        array  $summary = [],
        string $period  = ''
    ): string {
        $headerRow = implode('', array_map(fn($c) => "<th>{$c}</th>", $columns));
        $bodyRows  = implode('', array_map(function ($row) use ($columns) {
            $cells = implode('', array_map(
                fn($c) => '<td>' . htmlspecialchars((string)($row[$c] ?? ''), ENT_QUOTES) . '</td>',
                array_keys($columns)
            ));
            return "<tr>{$cells}</tr>";
        }, $data));

        $summaryHtml = '';
        if (!empty($summary)) {
            $rows = implode('', array_map(
                fn($k, $v) => "<tr><td><strong>{$k}</strong></td><td style='text-align:right'><strong>" . htmlspecialchars((string)$v) . "</strong></td></tr>",
                array_keys($summary), $summary
            ));
            $summaryHtml = "<h3>Summary</h3><table class='summary'>{$rows}</table>";
        }

        return "
        <style>
            body { font-family: dejavusans, Arial, sans-serif; font-size:9pt; color:#1a1a1a; }
            h1 { font-size:15pt; color:#4f46e5; margin:0 0 4px; }
            .period { font-size:8pt; color:#64748b; margin-bottom:12px; }
            table { width:100%; border-collapse:collapse; margin-bottom:16px; }
            th { background:#4f46e5; color:#fff; padding:7px 10px; font-size:8pt; text-align:left; }
            td { padding:6px 10px; border-bottom:1px solid #e2e8f0; font-size:8.5pt; }
            tr:nth-child(even) td { background:#f8fafc; }
            table.summary { width:260px; margin-left:auto; }
            table.summary td { border:1px solid #e2e8f0; }
        </style>
        <h1>{$reportTitle}</h1>
        <div class='period'>{$period}</div>
        <table><thead><tr>{$headerRow}</tr></thead><tbody>{$bodyRows}</tbody></table>
        {$summaryHtml}
        ";
    }

    // ── Pure-PHP XLSX builder ──────────────────────────────────────────────
    private static function buildXlsx(array $data, array $headers, string $sheetName): string
    {
        // Build shared strings
        $strings  = [];
        $strIndex = 0;
        $addStr   = function (string $s) use (&$strings, &$strIndex): int {
            if (!isset($strings[$s])) {
                $strings[$s] = $strIndex++;
            }
            return $strings[$s];
        };

        // Build row XML
        $rowXml = '';
        $rowNum = 1;

        // Header row
        $cells = '';
        foreach ($headers as $col => $header) {
            $colLetter = self::colLetter($col);
            $si        = $addStr((string)$header);
            $cells    .= "<c r=\"{$colLetter}{$rowNum}\" t=\"s\" s=\"1\"><v>{$si}</v></c>";
        }
        $rowXml .= "<row r=\"{$rowNum}\">{$cells}</row>";
        $rowNum++;

        // Data rows
        foreach ($data as $row) {
            $cells  = '';
            $colIdx = 0;
            $vals   = is_array($row) ? array_values($row) : [$row];
            foreach ($vals as $val) {
                $colLetter = self::colLetter($colIdx);
                if (is_numeric($val) && $val !== '') {
                    $cells .= "<c r=\"{$colLetter}{$rowNum}\" t=\"n\"><v>{$val}</v></c>";
                } else {
                    $si     = $addStr((string)$val);
                    $cells .= "<c r=\"{$colLetter}{$rowNum}\" t=\"s\"><v>{$si}</v></c>";
                }
                $colIdx++;
            }
            $rowXml .= "<row r=\"{$rowNum}\">{$cells}</row>";
            $rowNum++;
        }

        // Shared strings XML
        $ssiXml = implode('', array_map(
            fn($s) => '<si><t xml:space="preserve">' . htmlspecialchars($s, ENT_XML1) . '</t></si>',
            array_keys($strings)
        ));

        $files = [
            '_rels/.rels' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>',

            'xl/_rels/workbook.xml.rels' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>
<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>',

            '[Content_Types].xml' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml"  ContentType="application/xml"/>
<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
<Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>
<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
</Types>',

            'xl/workbook.xml' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
<sheets><sheet name="' . htmlspecialchars($sheetName, ENT_XML1) . '" sheetId="1" r:id="rId1"/></sheets>
</workbook>',

            'xl/sharedStrings.xml' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="' . count($strings) . '" uniqueCount="' . count($strings) . '">'
. $ssiXml . '</sst>',

            'xl/styles.xml' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<fonts><font><sz val="10"/><name val="Calibri"/></font><font><b/><sz val="10"/><name val="Calibri"/><color rgb="FFFFFFFF"/></font></fonts>
<fills><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill>
<fill><patternFill patternType="solid"><fgColor rgb="FF4F46E5"/></patternFill></fill></fills>
<borders><border><left/><right/><top/><bottom/><diagonal/></border></borders>
<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
<cellXfs>
<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
<xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/>
</cellXfs>
</styleSheet>',

            'xl/worksheets/sheet1.xml' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<sheetData>' . $rowXml . '</sheetData>
</worksheet>',
        ];

        return self::zipFiles($files);
    }

    private static function colLetter(int $index): string
    {
        $letter = '';
        $index++;
        while ($index > 0) {
            $mod    = ($index - 1) % 26;
            $letter = chr(65 + $mod) . $letter;
            $index  = (int)(($index - $mod) / 26);
        }
        return $letter;
    }

    /** Minimal pure-PHP ZIP builder (no extensions needed) */
    private static function zipFiles(array $files): string
    {
        $centralDir  = '';
        $localFiles  = '';
        $offset      = 0;

        foreach ($files as $name => $content) {
            $crc    = crc32($content);
            $size   = strlen($content);
            $time   = self::dosTime(time());

            $local = pack('VvvvVVVVvv', 0x04034b50, 20, 0, 0, $time, $crc, $size, $size, strlen($name), 0)
                   . $name . $content;

            $central = pack('VvvvvVVVVvvvvvVV', 0x02014b50, 20, 20, 0, 0, $time, $crc, $size, $size,
                            strlen($name), 0, 0, 0, 0, 0, $offset) . $name;

            $localFiles .= $local;
            $centralDir .= $central;
            $offset     += strlen($local);
        }

        $count = count($files);
        $eocd  = pack('VvvvvVVv', 0x06054b50, 0, 0, $count, $count,
                      strlen($centralDir), $offset, 0);

        return $localFiles . $centralDir . $eocd;
    }

    private static function dosTime(int $timestamp): int
    {
        $d = getdate($timestamp);
        return (($d['year'] - 1980) << 25) | ($d['mon'] << 21) | ($d['mday'] << 16)
             | ($d['hours'] << 11) | ($d['minutes'] << 5) | ($d['seconds'] >> 1);
    }

    private static function sanitizeFilename(string $name): string
    {
        return preg_replace('/[^a-zA-Z0-9_\-]/', '_', $name);
    }
}
